### ISSUE TITLE
Forward Application Exceptions for Triage (Email, Logging Service, Slack, GitHub Issue, Etc.) 

### ISSUE THREAD

**Issue by allella** [hackgvl/hackgreenville-com#216]
When a meetup group no longer exists the update_cal_data.py will catch an exception and log it.

I actually have the exception output emailed to me via the cronjob, but we should consider having these sorts of exceptions emailed, sent to a logging platform that sends notices, posted to a Slack channel, or otherwise shared with the people who can review and fix them.

Below is an example of when the Web Code Chicks group stopped using Meetup.com and we found out about it right away via the exception being emailed to me, but it could very well have gone unnoticed in a log.

We already have a tool that visits each organization's event service and homepage (I need to push this code to GitHub).  That makes this particular exception less necessary, but it demonstrates that we should do something more than just log the application's exceptions and errors. 

```
Traceback (most recent call last):

File "update_cal_data.py", line 25, in <module>
  refresh_all_meetings()
File "update_cal_data.py", line 10, in refresh_all_meetings
  meetup_events = app.get_meetup_events(group_lists['Meetup.com'])
File "app.py", line 52, in get_meetup_events
  raise Exception('Could not connect to Meetup API at {}.  Status Code: {}'.format(url, r.status_code))
Exception: Could not connect to Meetup API at https://api.meetup.com/webcodechicks/events?&sign=true&photo-host=public&page=20. Status Code: 410
```

**Comment by allella** [comment]
We have this going to a private HG Slack channel, so closing this issue and we can reopen or reference it as a need arises.
